// <auto-generated />
namespace ApiZadBackEnd.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Banke1UpdatePolje : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Banke1UpdatePolje));
        
        string IMigrationMetadata.Id
        {
            get { return "201804220903260_Banke1UpdatePolje"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
